### ISSUE TITLE
CMS

### ISSUE THREAD

**Issue by 10sr** [10sr/machine-setups#5]
なんか考える

ローカルで立てるとかだとやっぱり windows でめんどいのがめんどいので conoha 上に建てたい

静的ファイル生成する奴ではなく、自分自身がサーバになるタイプのやつ

**Comment by 10sr** [comment]
https://hexo.io/

**Comment by 10sr** [comment]
private にしたい、データの保存どうするのみたいなこと考えると、データそのものが git レポジトリ管理されるのがいいかなあ

**Comment by 10sr** [comment]
* データの取り回しが楽だといい
  * データベースに保存とかだと、それを取り出すのに dump 的なのが必要そうなイメージ

**Comment by 10sr** [comment]
自分で立てるのがメインじゃないっぽい
https://github.com/TryGhost/Ghost

**Comment by 10sr** [comment]
https://getnikola.com/

http://blog.getpelican.com/

**Comment by 10sr** [comment]
https://github.com/mgaitan/waliki

https://github.com/scragg0x/realms-wiki

https://github.com/mblayman/markwiki

**Comment by 10sr** [comment]
https://waliki.pythonanywhere.com/Git-powered-wiki-engines

The are a lot of wiki engine
Waliki 	Python/Django 	
Gollum 	Ruby/Sinatra 	
Realms 	Python/Flask 	
Smeagol 	Clojure 	
jingo 	nodejs 	
wigit 	PHP 	
ikiwiki 	Perl

**Comment by 10sr** [comment]
https://github.com/gollum/gollum

**Comment by 10sr** [comment]
realms-wiki
----------

https://github.com/scragg0x/realms-wiki

* pip でインストールする `pip install realms-wiki`
* ファイルが格納された git レポジトリが作られる
* ユーザ管理のために sqlite か他の DB を使う
  * コンテンツとは関係ないので、移動するのに必要はなさそう
* リアルタイムで他人と同時に編集するとかできる
* 閲覧制限はなさそう

### 設定ファイル

設定ファイルがないと、デフォルトの設定で動く。
そのため、「実行してるディレクトリ」みたいな概念がなくなるみたいなことになるけど、わかりにくい気がするので設定ファイルはいつも置くようにした方が良いと思う。

```
{
    "ALLOW_ANON": true,
    "BASE_URL": "http://localhost",
    "CACHE_TYPE": "simple",
    "DB_URI": "sqlite:///./wiki.db",
    "PORT": 5000,
    "REGISTRATION_ENABLED": true,
    "SEARCH_TYPE": "simple",
    "SECRET_KEY": "qgyo55oFleFuhOmND5zLTrk2z8YGQa3BA1n6OLIRfS51MpJ1NiXsuSmuCLcOpL7E",
    "SITE_TITLE": "Realms",
    "WIKI_PATH": "./data"
}
```

**Comment by 10sr** [comment]
waliki
=====

https://github.com/mgaitan/waliki

* Django のアプリ？
  * 多分 Django レポジトリ自体は自分で用意して、その INSTALLED_APPS に waliki を加える、という感じにやるんだと思う
* 試さないとわからないけどレポジトリ内にコンテンツ含めるのできそうな気がする

**Comment by 10sr** [comment]
markwiki
=======

https://github.com/mblayman/markwiki

* pip でインストールして `markwiki` で起動する
* なんか表示が崩れる…
* 設定項目は少し見つけづらいけど http://pythonhosted.org/MarkWiki/wiki/MarkWiki/Settings/

**Comment by 10sr** [comment]
melkor
=====

https://github.com/hiddentao/melkor

* npm でインストール
* `melkor` で起動。起動時のディレクトリに git init してそこにコンテンツをコミットしていく
* 設定は全部起動時の引数から行うっぽい
* 編集画面で保存ボタンが下にあって少し押しにくい
* アクセス制限は全くなさそうな雰囲気

**Comment by 10sr** [comment]
gollum
=====

https://github.com/gollum/gollum

* gem でインストール
* gollum で起動。起動時のディレクトリに git init してそこにコンテンツをコミットしていく
* 設定は全部起動時の引数から行うっぽい
  * 設定項目は melkor よりずっと多い
* 編集不可とか設定できる
  * 認証とかはできなそう

**Comment by 10sr** [comment]
wigit
====


https://github.com/remko/wigit/

* Textile かーというのと php よくわからないので後回し

**Comment by 10sr** [comment]
smeagol
=======

https://github.com/simon-brooke/smeagol
Closure

* closure かーこれだけのために closure 環境用意するのなーという感じなので後回し

**Comment by 10sr** [comment]
gitit
===

 https://github.com/jgm/gitit
Haskell

* haskell かーこれだけのために haskell 環境用意するのなーという感じなので後回し

**Comment by 10sr** [comment]
jingo
====

https://github.com/claudioc/jingo
Nodejs

* `npm install -g jingo` でインストール
* `jingo -s >config.yml` で設定ファイルを生成
* 内容は以下のような感じ

```
---
# Configuration sample file for Jingo (YAML)
application:
  title: Jingo
  repository: ''
  docSubdir: ''
  remote: ''
  pushInterval: 30
  secret: change me
  git: git
  skipGitCheck: false
  loggingMode: 1
  pedanticMarkdown: true
  gfmBreaks: true
  staticWhitelist: '/\.png$/i, /\.jpg$/i, /\.gif$/i'
  proxyPath: ''
authentication:
  google:
    enabled: true
    clientId: replace me with the real value
    clientSecret: replace me with the real value
    redirectURL: ''
  github:
    enabled: false
    clientId: replace me with the real value
    clientSecret: replace me with the real value
    redirectURL: ''
  local:
    enabled: false
    accounts:
      - username: ''
        passwordHash: ''
        email: ''
features:
  markitup: false
  codemirror: true
server:
  hostname: localhost
  port: 6067
  localOnly: false
  baseUrl: ''
  CORS:
    enabled: false
    allowedOrigin: '*'
authorization:
  anonRead: true
  validMatches: .+
  emptyEmailMatches: false
pages:
  index: Home
  title:
    fromFilename: true
    fromContent: false
    asciiOnly: false
    lowercase: false
  itemsPerPage: 10
customizations:
  sidebar: _sidebar.md
  footer: _footer.md
  style: _style.css
  script: _script.js
```
